apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: application
  # annotations: 
    # traefik.ingress.kubernetes.io/router.middlewares: application-mw-admin@kubernetescrd
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /whoami
            pathType: Prefix
            backend:
              service:
                name: whoami-svc
                port:
                  number: 80
          - path: /vue
            pathType: Prefix
            backend:
              service:
                name: vue-svc
                port:
                  number: 80
          - path: /consumer
            pathType: Prefix
            backend:
              service:
                name: backend-consumer-svc
                port:
                  number: 80
          - path: /producer
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 80           
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-server-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /grafana/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: loki-stack-grafana
                port:
                  number: 80
          - path: /argocd/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: argocd-svc-external
                port:
                  number: 80        
---
apiVersion: v1 
kind: Service
metadata:
  name: argocd-svc-external
  namespace: monitoring
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
