apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: application
  annotations: 
    traefik.ingress.kubernetes.io/router.middlewares: application-mw-admin@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /whoami
            pathType: Prefix
            backend:
              service:
                name: whoami-svc
                port:
                  number: 80
          - path: /vue
            pathType: Prefix
            backend:
              service:
                name: vue-svc
                port:
                  number: 80
          - path: /consumer
            pathType: Prefix
            backend:
              service:
                name: backend-consumer-svc
                port:
                  number: 80
          - path: /producer
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 80
---
# # Middleware
# # Strip prefix /overview
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: mw-admin
  namespace: application
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /vue
      - /consumer
      - /producer
    