apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vue-app
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: vue-app
spec:
  # The project the application belongs to.
  project: pyproject
  source:
    repoURL: https://github.com/hlehaeger/argocd-example.git 
    targetRevision: HEAD
    path: frontend
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: application
  syncPolicy:
    manual:
      prune: true
      selfHeal: true
      allowEmpty: false