apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-app
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: mongo-app
spec:
  # The project the application belongs to.
  project: pyproject
  source:
    repoURL: https://github.com/hlehaeger/argocd-example.git
    targetRevision: HEAD
    path: mongodb
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false