apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-consumer
  labels:
    app: backend-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-consumer
  template:
    metadata:
      labels:
        app: backend-consumer
    spec:
      containers:
      - name: backend-consumer
        image: lehieu1408/pythonkafka-consumer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"            
---
apiVersion: v1
kind: Service
metadata:
  name: backend-consumer-svc
spec:
  selector:
    app: backend-consumer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP            